### ISSUE TITLE
UI breaks when wavs are corrupted

### ISSUE THREAD

**Issue by WillNilges** [sgreene570/sampleZone#6]
A message will pop up in the middle of the UI and break everything. This message should be moved somewhere else, or should halt the program.
![image](https://user-images.githubusercontent.com/42927786/51503174-9b137b80-1da7-11e9-80b0-9a98002ccccb.png)

**Comment by sgreene570** [comment]
Can probably check validity of wav files before grid is loading and exit on error or something like that

**Comment by WillNilges** [comment]
I got a basic fix working last night. I'll make a PR tonight and keep working on a more robust solution.

**Comment by sgreene570** [comment]
awesome
